alter table public.products
  add column if not exists current_price_krw integer;

update public.products
set current_price_krw = round(price / exchange_rate)
where current_price_krw is null
  and price is not null
  and exchange_rate is not null
  and exchange_rate > 0;

alter table public.products
  drop constraint if exists products_current_price_krw_positive_check,
  add constraint products_current_price_krw_positive_check
    check (current_price_krw is null or current_price_krw > 0);

create table if not exists public.product_sizes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  size text not null,
  price_krw integer not null check (price_krw > 0),
  created_at timestamptz not null default now(),
  unique (product_id, size)
);

create index if not exists product_sizes_product_id_idx on public.product_sizes(product_id);